### ISSUE TITLE
Can't use Alt Name pair in some commands

### ISSUE THREAD

**Issue by mcastillof** [zertrin/clikraken#20]
Placing orders using Alt Names is working fine, but other commands are failing.

```
(clikraken) dodo@santiago:~ $ clikraken place -v sell 200 200 -p XETHXXBT
sell 200.00000000 ETHXBT @ limit 200.00000
INFO     - Validating inputs only. Order not submitted!
(clikraken) dodo@santiago:~ $ clikraken place -v sell 200 200 -p ETHXBT
sell 200.00000000 ETHXBT @ limit 200.00000
INFO     - Validating inputs only. Order not submitted!
(clikraken) dodo@santiago:~ $ clikraken depth -p XETHXXBT
  ETHXBT Ask    Volume  Age
------------  --------  ----------
     0.05977    47.905  in 2 hours
     0.05976    46.513  in 2 hours
     0.05971    29.332  in 2 hours
     0.0597     46.805  in 2 hours
     0.05969    46.558  in 2 hours
     0.05964     3.544  in 2 hours
     0.0596      0.705  in 2 hours

  ETHXBT Bid    Volume  Age
------------  --------  ----------
     0.05959     1.183  in 2 hours
     0.05958     1.35   in 2 hours
     0.05955    56.582  in 2 hours
     0.05954   163.661  in 2 hours
     0.05953    80.552  in 2 hours
     0.05952    51.752  in 2 hours
     0.05951    14.281  in 2 hours
(clikraken) dodo@santiago:~ $ clikraken depth -p ETHXBT
Traceback (most recent call last):
  File "/home/dodo/.venv/clikraken/bin/clikraken", line 11, in <module>
    sys.exit(main())
  File "/home/dodo/.venv/clikraken/lib/python3.4/site-packages/clikraken/clikraken.py", line 32, in main
    func(args)
  File "/home/dodo/.venv/clikraken/lib/python3.4/site-packages/clikraken/api/public/depth.py", line 40, in depth
    dlist = res[args.pair][dtype]
KeyError: 'ETHXBT'
(clikraken) dodo@santiago:~ $ clikraken lt -p XETHXXBT
Trade type    Order type      Price      Volume  Age
------------  ------------  -------  ----------  ----------
sell          market        0.05972  0.26329     in 2 hours
sell          limit         0.05972  2.82349554  in 2 hours
sell          limit         0.05979  1.57650446  in 2 hours
sell          limit         0.05979  0.17077     in 2 hours
sell          limit         0.05979  0.25272554  in 2 hours
sell          limit         0.05979  0.09138609  in 2 hours
sell          limit         0.05972  0.029848    in 2 hours
buy           market        0.05979  0.266       in 2 hours
buy           market        0.05976  0.575       in 2 hours
buy           limit         0.05976  0.02469966  in 2 hours
buy           limit         0.05977  0.2913855   in 2 hours
sell          limit         0.05973  0.78786356  in 2 hours
buy           limit         0.05977  0.20537538  in 2 hours
buy           limit         0.05972  0.17124167  in 2 hours
sell          market        0.0597   9           in 2 hours

             Price (XBT)    Volume  Age
---------  -------------  --------  ----------
Last Sell        0.05972   0.26329  in 2 hours
Last Buy         0.05979   0.266    in 2 hours

Last ID = 1508159414417974409
(clikraken) dodo@santiago:~ $ clikraken lt -p ETHXBT
Traceback (most recent call last):
  File "/home/dodo/.venv/clikraken/bin/clikraken", line 11, in <module>
    sys.exit(main())
  File "/home/dodo/.venv/clikraken/lib/python3.4/site-packages/clikraken/clikraken.py", line 32, in main
    func(args)
  File "/home/dodo/.venv/clikraken/lib/python3.4/site-packages/clikraken/api/public/last_trades.py", line 34, in last_trades
    results = res[args.pair]
KeyError: 'ETHXBT'
```

**Comment by zertrin** [comment]
Closing as I won't be maintaining this project any more.

Thanks though!
