### ISSUE TITLE
clikraken: command not found

### ISSUE THREAD

**Issue by overseers-desk** [zertrin/clikraken#27]
I'm following the instruction on README.md (except didn't use virtualenv). After installing with

$ pip install clikraken

successfully, typing clikraken would result "command not found".

I tried to

```
$ cd .local/lib/python3.5/site-packages/clikraken
$ python3 clikraken/clikraken.py 
Traceback (most recent call last):
  File "clikraken/clikraken.py", line 12, in <module>
    from clikraken.api.api_utils import load_api_keyfile
  File "/home/weiwu/.local/lib/python3.5/site-packages/clikraken/clikraken.py", line 12, in <module>
    from clikraken.api.api_utils import load_api_keyfile
ImportError: No module named 'clikraken.api'; 'clikraken' is not a package
```

**Comment by zertrin** [comment]
If you insist on using clikraken like this (which I don't recommend), then you need to call it like this: 

`python -m clikraken`
