### ISSUE TITLE
JSONDecodeError for Place Order

### ISSUE THREAD

**Issue by a1492dc** [zertrin/clikraken#28]
I'm able to run most of the commands public and private (ticker, balance), but when I try to submit an order with the following command:
`clikraken place -v buy 1 -t market -p BCHEUR `

I get the following error:
```
`(clikraken) alfredo@agr:~$ clikraken ticker -p XRPEUR
pair      last     high     low            vol        wavg  vol value        ask    bid
------  ------  -------  ------  -------------  ----------  -----------  -------  -----
XRPEUR   0.283  0.32956  0.1961  49940819.8232  0.24684225  12 MEUR      0.28506  0.283
```
```
(clikraken) alfredo@agr:~$ clikraken place -v buy 1 -t market -p XRPEUR
ERROR    - ValueError while querying Kraken API!
Traceback (most recent call last):
  File "/home/alfredo/.venv/clikraken/lib/python3.5/site-packages/clikraken/api/api_utils.py", line 68, in query_api
    res = func(api_method, api_params)
  File "/home/alfredo/.venv/clikraken/lib/python3.5/site-packages/krakenex/api.py", line 182, in query_private
    return self._query(urlpath, req, conn, headers)
  File "/home/alfredo/.venv/clikraken/lib/python3.5/site-packages/krakenex/api.py", line 131, in _query
    return json.loads(ret)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
`

**Comment by zertrin** [comment]
Once again a problem from kraken api being completely overloaded in the last few months.

Nothing I can do, except maybe catching that exception and outputting a better error message.

But really, kraken should fix their api not to reply invalid json at the first place...

**Comment by a1492dc** [comment]
Thanks for your quick reply :)

**Comment by zertrin** [comment]
I changed the handling of the exception in commit cec46ae0 

Now the error looks like this:

    ERROR    - Invalid response from Kraken API! (This can happen when Kraken API is overloaded. Try your luck again later.)
    ERROR    - Error details: JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)
